name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Sujal829

      - name: Commit Pacman output
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Add Pacman contribution graph"
          add: "output-pacman"
