name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@v2.0.1
        with:
          github_user_name: Sujal829

      - name: Replace output folder
        run: |
          rm -rf output-pacman
          mv output output-pacman

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update pacman contribution graph"
          add: "output-pacman"
