name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Sujal829

      - name: Prepare output branch
        run: |
          git checkout output || git checkout -b output

      - name: Update pacman files
        run: |
          rm -rf output-pacman
          mv output output-pacman

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output-pacman
          git commit -m "chore: update pacman contribution graph" || echo "No changes"
          git push origin output
