name: Generate Pacman Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Sujal829

      - name: Debug folders
        run: ls -la

      - name: Switch to output branch
        run: |
          git checkout output || git checkout -b output

      - name: Move generated files
        run: |
          rm -rf output-pacman
          
          if [ -d "output" ]; then
            mv output output-pacman
          elif [ -d "dist" ]; then
            mv dist output-pacman
          elif [ -d "pacman" ]; then
            mv pacman output-pacman
          else
            echo "‚ùå No pacman output folder found"
            exit 1
          fi

      - name: Commit & push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output-pacman
          git commit -m "chore: update pacman contribution graph" || echo "No changes"
          git push origin output
