name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Sujal829

      - name: Commit output
        uses: EndBug/add-and-commit@v9
        with:
          message: "Add Pacman contribution graph"
          add: "output"
